// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package io.etcd.jetcd.api;

/**
 * Protobuf type {@code etcdserverpb.ResponseOp}
 */
public  final class ResponseOp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:etcdserverpb.ResponseOp)
    ResponseOpOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResponseOp.newBuilder() to construct.
  private ResponseOp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResponseOp() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ResponseOp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            io.etcd.jetcd.api.RangeResponse.Builder subBuilder = null;
            if (responseCase_ == 1) {
              subBuilder = ((io.etcd.jetcd.api.RangeResponse) response_).toBuilder();
            }
            response_ =
                input.readMessage(io.etcd.jetcd.api.RangeResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.etcd.jetcd.api.RangeResponse) response_);
              response_ = subBuilder.buildPartial();
            }
            responseCase_ = 1;
            break;
          }
          case 18: {
            io.etcd.jetcd.api.PutResponse.Builder subBuilder = null;
            if (responseCase_ == 2) {
              subBuilder = ((io.etcd.jetcd.api.PutResponse) response_).toBuilder();
            }
            response_ =
                input.readMessage(io.etcd.jetcd.api.PutResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.etcd.jetcd.api.PutResponse) response_);
              response_ = subBuilder.buildPartial();
            }
            responseCase_ = 2;
            break;
          }
          case 26: {
            io.etcd.jetcd.api.DeleteRangeResponse.Builder subBuilder = null;
            if (responseCase_ == 3) {
              subBuilder = ((io.etcd.jetcd.api.DeleteRangeResponse) response_).toBuilder();
            }
            response_ =
                input.readMessage(io.etcd.jetcd.api.DeleteRangeResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.etcd.jetcd.api.DeleteRangeResponse) response_);
              response_ = subBuilder.buildPartial();
            }
            responseCase_ = 3;
            break;
          }
          case 34: {
            io.etcd.jetcd.api.TxnResponse.Builder subBuilder = null;
            if (responseCase_ == 4) {
              subBuilder = ((io.etcd.jetcd.api.TxnResponse) response_).toBuilder();
            }
            response_ =
                input.readMessage(io.etcd.jetcd.api.TxnResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.etcd.jetcd.api.TxnResponse) response_);
              response_ = subBuilder.buildPartial();
            }
            responseCase_ = 4;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.etcd.jetcd.api.JetcdProto.internal_static_etcdserverpb_ResponseOp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.etcd.jetcd.api.JetcdProto.internal_static_etcdserverpb_ResponseOp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.etcd.jetcd.api.ResponseOp.class, io.etcd.jetcd.api.ResponseOp.Builder.class);
  }

  private int responseCase_ = 0;
  private java.lang.Object response_;
  public enum ResponseCase
      implements com.google.protobuf.Internal.EnumLite {
    RESPONSE_RANGE(1),
    RESPONSE_PUT(2),
    RESPONSE_DELETE_RANGE(3),
    RESPONSE_TXN(4),
    RESPONSE_NOT_SET(0);
    private final int value;
    private ResponseCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResponseCase valueOf(int value) {
      return forNumber(value);
    }

    public static ResponseCase forNumber(int value) {
      switch (value) {
        case 1: return RESPONSE_RANGE;
        case 2: return RESPONSE_PUT;
        case 3: return RESPONSE_DELETE_RANGE;
        case 4: return RESPONSE_TXN;
        case 0: return RESPONSE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ResponseCase
  getResponseCase() {
    return ResponseCase.forNumber(
        responseCase_);
  }

  public static final int RESPONSE_RANGE_FIELD_NUMBER = 1;
  /**
   * <code>.etcdserverpb.RangeResponse response_range = 1;</code>
   */
  public boolean hasResponseRange() {
    return responseCase_ == 1;
  }
  /**
   * <code>.etcdserverpb.RangeResponse response_range = 1;</code>
   */
  public io.etcd.jetcd.api.RangeResponse getResponseRange() {
    if (responseCase_ == 1) {
       return (io.etcd.jetcd.api.RangeResponse) response_;
    }
    return io.etcd.jetcd.api.RangeResponse.getDefaultInstance();
  }
  /**
   * <code>.etcdserverpb.RangeResponse response_range = 1;</code>
   */
  public io.etcd.jetcd.api.RangeResponseOrBuilder getResponseRangeOrBuilder() {
    if (responseCase_ == 1) {
       return (io.etcd.jetcd.api.RangeResponse) response_;
    }
    return io.etcd.jetcd.api.RangeResponse.getDefaultInstance();
  }

  public static final int RESPONSE_PUT_FIELD_NUMBER = 2;
  /**
   * <code>.etcdserverpb.PutResponse response_put = 2;</code>
   */
  public boolean hasResponsePut() {
    return responseCase_ == 2;
  }
  /**
   * <code>.etcdserverpb.PutResponse response_put = 2;</code>
   */
  public io.etcd.jetcd.api.PutResponse getResponsePut() {
    if (responseCase_ == 2) {
       return (io.etcd.jetcd.api.PutResponse) response_;
    }
    return io.etcd.jetcd.api.PutResponse.getDefaultInstance();
  }
  /**
   * <code>.etcdserverpb.PutResponse response_put = 2;</code>
   */
  public io.etcd.jetcd.api.PutResponseOrBuilder getResponsePutOrBuilder() {
    if (responseCase_ == 2) {
       return (io.etcd.jetcd.api.PutResponse) response_;
    }
    return io.etcd.jetcd.api.PutResponse.getDefaultInstance();
  }

  public static final int RESPONSE_DELETE_RANGE_FIELD_NUMBER = 3;
  /**
   * <code>.etcdserverpb.DeleteRangeResponse response_delete_range = 3;</code>
   */
  public boolean hasResponseDeleteRange() {
    return responseCase_ == 3;
  }
  /**
   * <code>.etcdserverpb.DeleteRangeResponse response_delete_range = 3;</code>
   */
  public io.etcd.jetcd.api.DeleteRangeResponse getResponseDeleteRange() {
    if (responseCase_ == 3) {
       return (io.etcd.jetcd.api.DeleteRangeResponse) response_;
    }
    return io.etcd.jetcd.api.DeleteRangeResponse.getDefaultInstance();
  }
  /**
   * <code>.etcdserverpb.DeleteRangeResponse response_delete_range = 3;</code>
   */
  public io.etcd.jetcd.api.DeleteRangeResponseOrBuilder getResponseDeleteRangeOrBuilder() {
    if (responseCase_ == 3) {
       return (io.etcd.jetcd.api.DeleteRangeResponse) response_;
    }
    return io.etcd.jetcd.api.DeleteRangeResponse.getDefaultInstance();
  }

  public static final int RESPONSE_TXN_FIELD_NUMBER = 4;
  /**
   * <code>.etcdserverpb.TxnResponse response_txn = 4;</code>
   */
  public boolean hasResponseTxn() {
    return responseCase_ == 4;
  }
  /**
   * <code>.etcdserverpb.TxnResponse response_txn = 4;</code>
   */
  public io.etcd.jetcd.api.TxnResponse getResponseTxn() {
    if (responseCase_ == 4) {
       return (io.etcd.jetcd.api.TxnResponse) response_;
    }
    return io.etcd.jetcd.api.TxnResponse.getDefaultInstance();
  }
  /**
   * <code>.etcdserverpb.TxnResponse response_txn = 4;</code>
   */
  public io.etcd.jetcd.api.TxnResponseOrBuilder getResponseTxnOrBuilder() {
    if (responseCase_ == 4) {
       return (io.etcd.jetcd.api.TxnResponse) response_;
    }
    return io.etcd.jetcd.api.TxnResponse.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (responseCase_ == 1) {
      output.writeMessage(1, (io.etcd.jetcd.api.RangeResponse) response_);
    }
    if (responseCase_ == 2) {
      output.writeMessage(2, (io.etcd.jetcd.api.PutResponse) response_);
    }
    if (responseCase_ == 3) {
      output.writeMessage(3, (io.etcd.jetcd.api.DeleteRangeResponse) response_);
    }
    if (responseCase_ == 4) {
      output.writeMessage(4, (io.etcd.jetcd.api.TxnResponse) response_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (responseCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (io.etcd.jetcd.api.RangeResponse) response_);
    }
    if (responseCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (io.etcd.jetcd.api.PutResponse) response_);
    }
    if (responseCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (io.etcd.jetcd.api.DeleteRangeResponse) response_);
    }
    if (responseCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (io.etcd.jetcd.api.TxnResponse) response_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.etcd.jetcd.api.ResponseOp)) {
      return super.equals(obj);
    }
    io.etcd.jetcd.api.ResponseOp other = (io.etcd.jetcd.api.ResponseOp) obj;

    boolean result = true;
    result = result && getResponseCase().equals(
        other.getResponseCase());
    if (!result) return false;
    switch (responseCase_) {
      case 1:
        result = result && getResponseRange()
            .equals(other.getResponseRange());
        break;
      case 2:
        result = result && getResponsePut()
            .equals(other.getResponsePut());
        break;
      case 3:
        result = result && getResponseDeleteRange()
            .equals(other.getResponseDeleteRange());
        break;
      case 4:
        result = result && getResponseTxn()
            .equals(other.getResponseTxn());
        break;
      case 0:
      default:
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (responseCase_) {
      case 1:
        hash = (37 * hash) + RESPONSE_RANGE_FIELD_NUMBER;
        hash = (53 * hash) + getResponseRange().hashCode();
        break;
      case 2:
        hash = (37 * hash) + RESPONSE_PUT_FIELD_NUMBER;
        hash = (53 * hash) + getResponsePut().hashCode();
        break;
      case 3:
        hash = (37 * hash) + RESPONSE_DELETE_RANGE_FIELD_NUMBER;
        hash = (53 * hash) + getResponseDeleteRange().hashCode();
        break;
      case 4:
        hash = (37 * hash) + RESPONSE_TXN_FIELD_NUMBER;
        hash = (53 * hash) + getResponseTxn().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.etcd.jetcd.api.ResponseOp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.etcd.jetcd.api.ResponseOp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.etcd.jetcd.api.ResponseOp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.etcd.jetcd.api.ResponseOp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.etcd.jetcd.api.ResponseOp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.etcd.jetcd.api.ResponseOp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.etcd.jetcd.api.ResponseOp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.etcd.jetcd.api.ResponseOp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.etcd.jetcd.api.ResponseOp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.etcd.jetcd.api.ResponseOp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.etcd.jetcd.api.ResponseOp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.etcd.jetcd.api.ResponseOp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.etcd.jetcd.api.ResponseOp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code etcdserverpb.ResponseOp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:etcdserverpb.ResponseOp)
      io.etcd.jetcd.api.ResponseOpOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.etcd.jetcd.api.JetcdProto.internal_static_etcdserverpb_ResponseOp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.etcd.jetcd.api.JetcdProto.internal_static_etcdserverpb_ResponseOp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.etcd.jetcd.api.ResponseOp.class, io.etcd.jetcd.api.ResponseOp.Builder.class);
    }

    // Construct using io.etcd.jetcd.api.ResponseOp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      responseCase_ = 0;
      response_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.etcd.jetcd.api.JetcdProto.internal_static_etcdserverpb_ResponseOp_descriptor;
    }

    @java.lang.Override
    public io.etcd.jetcd.api.ResponseOp getDefaultInstanceForType() {
      return io.etcd.jetcd.api.ResponseOp.getDefaultInstance();
    }

    @java.lang.Override
    public io.etcd.jetcd.api.ResponseOp build() {
      io.etcd.jetcd.api.ResponseOp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.etcd.jetcd.api.ResponseOp buildPartial() {
      io.etcd.jetcd.api.ResponseOp result = new io.etcd.jetcd.api.ResponseOp(this);
      if (responseCase_ == 1) {
        if (responseRangeBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = responseRangeBuilder_.build();
        }
      }
      if (responseCase_ == 2) {
        if (responsePutBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = responsePutBuilder_.build();
        }
      }
      if (responseCase_ == 3) {
        if (responseDeleteRangeBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = responseDeleteRangeBuilder_.build();
        }
      }
      if (responseCase_ == 4) {
        if (responseTxnBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = responseTxnBuilder_.build();
        }
      }
      result.responseCase_ = responseCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.etcd.jetcd.api.ResponseOp) {
        return mergeFrom((io.etcd.jetcd.api.ResponseOp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.etcd.jetcd.api.ResponseOp other) {
      if (other == io.etcd.jetcd.api.ResponseOp.getDefaultInstance()) return this;
      switch (other.getResponseCase()) {
        case RESPONSE_RANGE: {
          mergeResponseRange(other.getResponseRange());
          break;
        }
        case RESPONSE_PUT: {
          mergeResponsePut(other.getResponsePut());
          break;
        }
        case RESPONSE_DELETE_RANGE: {
          mergeResponseDeleteRange(other.getResponseDeleteRange());
          break;
        }
        case RESPONSE_TXN: {
          mergeResponseTxn(other.getResponseTxn());
          break;
        }
        case RESPONSE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.etcd.jetcd.api.ResponseOp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.etcd.jetcd.api.ResponseOp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int responseCase_ = 0;
    private java.lang.Object response_;
    public ResponseCase
        getResponseCase() {
      return ResponseCase.forNumber(
          responseCase_);
    }

    public Builder clearResponse() {
      responseCase_ = 0;
      response_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        io.etcd.jetcd.api.RangeResponse, io.etcd.jetcd.api.RangeResponse.Builder, io.etcd.jetcd.api.RangeResponseOrBuilder> responseRangeBuilder_;
    /**
     * <code>.etcdserverpb.RangeResponse response_range = 1;</code>
     */
    public boolean hasResponseRange() {
      return responseCase_ == 1;
    }
    /**
     * <code>.etcdserverpb.RangeResponse response_range = 1;</code>
     */
    public io.etcd.jetcd.api.RangeResponse getResponseRange() {
      if (responseRangeBuilder_ == null) {
        if (responseCase_ == 1) {
          return (io.etcd.jetcd.api.RangeResponse) response_;
        }
        return io.etcd.jetcd.api.RangeResponse.getDefaultInstance();
      } else {
        if (responseCase_ == 1) {
          return responseRangeBuilder_.getMessage();
        }
        return io.etcd.jetcd.api.RangeResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.etcdserverpb.RangeResponse response_range = 1;</code>
     */
    public Builder setResponseRange(io.etcd.jetcd.api.RangeResponse value) {
      if (responseRangeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        response_ = value;
        onChanged();
      } else {
        responseRangeBuilder_.setMessage(value);
      }
      responseCase_ = 1;
      return this;
    }
    /**
     * <code>.etcdserverpb.RangeResponse response_range = 1;</code>
     */
    public Builder setResponseRange(
        io.etcd.jetcd.api.RangeResponse.Builder builderForValue) {
      if (responseRangeBuilder_ == null) {
        response_ = builderForValue.build();
        onChanged();
      } else {
        responseRangeBuilder_.setMessage(builderForValue.build());
      }
      responseCase_ = 1;
      return this;
    }
    /**
     * <code>.etcdserverpb.RangeResponse response_range = 1;</code>
     */
    public Builder mergeResponseRange(io.etcd.jetcd.api.RangeResponse value) {
      if (responseRangeBuilder_ == null) {
        if (responseCase_ == 1 &&
            response_ != io.etcd.jetcd.api.RangeResponse.getDefaultInstance()) {
          response_ = io.etcd.jetcd.api.RangeResponse.newBuilder((io.etcd.jetcd.api.RangeResponse) response_)
              .mergeFrom(value).buildPartial();
        } else {
          response_ = value;
        }
        onChanged();
      } else {
        if (responseCase_ == 1) {
          responseRangeBuilder_.mergeFrom(value);
        }
        responseRangeBuilder_.setMessage(value);
      }
      responseCase_ = 1;
      return this;
    }
    /**
     * <code>.etcdserverpb.RangeResponse response_range = 1;</code>
     */
    public Builder clearResponseRange() {
      if (responseRangeBuilder_ == null) {
        if (responseCase_ == 1) {
          responseCase_ = 0;
          response_ = null;
          onChanged();
        }
      } else {
        if (responseCase_ == 1) {
          responseCase_ = 0;
          response_ = null;
        }
        responseRangeBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.etcdserverpb.RangeResponse response_range = 1;</code>
     */
    public io.etcd.jetcd.api.RangeResponse.Builder getResponseRangeBuilder() {
      return getResponseRangeFieldBuilder().getBuilder();
    }
    /**
     * <code>.etcdserverpb.RangeResponse response_range = 1;</code>
     */
    public io.etcd.jetcd.api.RangeResponseOrBuilder getResponseRangeOrBuilder() {
      if ((responseCase_ == 1) && (responseRangeBuilder_ != null)) {
        return responseRangeBuilder_.getMessageOrBuilder();
      } else {
        if (responseCase_ == 1) {
          return (io.etcd.jetcd.api.RangeResponse) response_;
        }
        return io.etcd.jetcd.api.RangeResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.etcdserverpb.RangeResponse response_range = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.etcd.jetcd.api.RangeResponse, io.etcd.jetcd.api.RangeResponse.Builder, io.etcd.jetcd.api.RangeResponseOrBuilder> 
        getResponseRangeFieldBuilder() {
      if (responseRangeBuilder_ == null) {
        if (!(responseCase_ == 1)) {
          response_ = io.etcd.jetcd.api.RangeResponse.getDefaultInstance();
        }
        responseRangeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.etcd.jetcd.api.RangeResponse, io.etcd.jetcd.api.RangeResponse.Builder, io.etcd.jetcd.api.RangeResponseOrBuilder>(
                (io.etcd.jetcd.api.RangeResponse) response_,
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      responseCase_ = 1;
      onChanged();;
      return responseRangeBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.etcd.jetcd.api.PutResponse, io.etcd.jetcd.api.PutResponse.Builder, io.etcd.jetcd.api.PutResponseOrBuilder> responsePutBuilder_;
    /**
     * <code>.etcdserverpb.PutResponse response_put = 2;</code>
     */
    public boolean hasResponsePut() {
      return responseCase_ == 2;
    }
    /**
     * <code>.etcdserverpb.PutResponse response_put = 2;</code>
     */
    public io.etcd.jetcd.api.PutResponse getResponsePut() {
      if (responsePutBuilder_ == null) {
        if (responseCase_ == 2) {
          return (io.etcd.jetcd.api.PutResponse) response_;
        }
        return io.etcd.jetcd.api.PutResponse.getDefaultInstance();
      } else {
        if (responseCase_ == 2) {
          return responsePutBuilder_.getMessage();
        }
        return io.etcd.jetcd.api.PutResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.etcdserverpb.PutResponse response_put = 2;</code>
     */
    public Builder setResponsePut(io.etcd.jetcd.api.PutResponse value) {
      if (responsePutBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        response_ = value;
        onChanged();
      } else {
        responsePutBuilder_.setMessage(value);
      }
      responseCase_ = 2;
      return this;
    }
    /**
     * <code>.etcdserverpb.PutResponse response_put = 2;</code>
     */
    public Builder setResponsePut(
        io.etcd.jetcd.api.PutResponse.Builder builderForValue) {
      if (responsePutBuilder_ == null) {
        response_ = builderForValue.build();
        onChanged();
      } else {
        responsePutBuilder_.setMessage(builderForValue.build());
      }
      responseCase_ = 2;
      return this;
    }
    /**
     * <code>.etcdserverpb.PutResponse response_put = 2;</code>
     */
    public Builder mergeResponsePut(io.etcd.jetcd.api.PutResponse value) {
      if (responsePutBuilder_ == null) {
        if (responseCase_ == 2 &&
            response_ != io.etcd.jetcd.api.PutResponse.getDefaultInstance()) {
          response_ = io.etcd.jetcd.api.PutResponse.newBuilder((io.etcd.jetcd.api.PutResponse) response_)
              .mergeFrom(value).buildPartial();
        } else {
          response_ = value;
        }
        onChanged();
      } else {
        if (responseCase_ == 2) {
          responsePutBuilder_.mergeFrom(value);
        }
        responsePutBuilder_.setMessage(value);
      }
      responseCase_ = 2;
      return this;
    }
    /**
     * <code>.etcdserverpb.PutResponse response_put = 2;</code>
     */
    public Builder clearResponsePut() {
      if (responsePutBuilder_ == null) {
        if (responseCase_ == 2) {
          responseCase_ = 0;
          response_ = null;
          onChanged();
        }
      } else {
        if (responseCase_ == 2) {
          responseCase_ = 0;
          response_ = null;
        }
        responsePutBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.etcdserverpb.PutResponse response_put = 2;</code>
     */
    public io.etcd.jetcd.api.PutResponse.Builder getResponsePutBuilder() {
      return getResponsePutFieldBuilder().getBuilder();
    }
    /**
     * <code>.etcdserverpb.PutResponse response_put = 2;</code>
     */
    public io.etcd.jetcd.api.PutResponseOrBuilder getResponsePutOrBuilder() {
      if ((responseCase_ == 2) && (responsePutBuilder_ != null)) {
        return responsePutBuilder_.getMessageOrBuilder();
      } else {
        if (responseCase_ == 2) {
          return (io.etcd.jetcd.api.PutResponse) response_;
        }
        return io.etcd.jetcd.api.PutResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.etcdserverpb.PutResponse response_put = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.etcd.jetcd.api.PutResponse, io.etcd.jetcd.api.PutResponse.Builder, io.etcd.jetcd.api.PutResponseOrBuilder> 
        getResponsePutFieldBuilder() {
      if (responsePutBuilder_ == null) {
        if (!(responseCase_ == 2)) {
          response_ = io.etcd.jetcd.api.PutResponse.getDefaultInstance();
        }
        responsePutBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.etcd.jetcd.api.PutResponse, io.etcd.jetcd.api.PutResponse.Builder, io.etcd.jetcd.api.PutResponseOrBuilder>(
                (io.etcd.jetcd.api.PutResponse) response_,
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      responseCase_ = 2;
      onChanged();;
      return responsePutBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.etcd.jetcd.api.DeleteRangeResponse, io.etcd.jetcd.api.DeleteRangeResponse.Builder, io.etcd.jetcd.api.DeleteRangeResponseOrBuilder> responseDeleteRangeBuilder_;
    /**
     * <code>.etcdserverpb.DeleteRangeResponse response_delete_range = 3;</code>
     */
    public boolean hasResponseDeleteRange() {
      return responseCase_ == 3;
    }
    /**
     * <code>.etcdserverpb.DeleteRangeResponse response_delete_range = 3;</code>
     */
    public io.etcd.jetcd.api.DeleteRangeResponse getResponseDeleteRange() {
      if (responseDeleteRangeBuilder_ == null) {
        if (responseCase_ == 3) {
          return (io.etcd.jetcd.api.DeleteRangeResponse) response_;
        }
        return io.etcd.jetcd.api.DeleteRangeResponse.getDefaultInstance();
      } else {
        if (responseCase_ == 3) {
          return responseDeleteRangeBuilder_.getMessage();
        }
        return io.etcd.jetcd.api.DeleteRangeResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.etcdserverpb.DeleteRangeResponse response_delete_range = 3;</code>
     */
    public Builder setResponseDeleteRange(io.etcd.jetcd.api.DeleteRangeResponse value) {
      if (responseDeleteRangeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        response_ = value;
        onChanged();
      } else {
        responseDeleteRangeBuilder_.setMessage(value);
      }
      responseCase_ = 3;
      return this;
    }
    /**
     * <code>.etcdserverpb.DeleteRangeResponse response_delete_range = 3;</code>
     */
    public Builder setResponseDeleteRange(
        io.etcd.jetcd.api.DeleteRangeResponse.Builder builderForValue) {
      if (responseDeleteRangeBuilder_ == null) {
        response_ = builderForValue.build();
        onChanged();
      } else {
        responseDeleteRangeBuilder_.setMessage(builderForValue.build());
      }
      responseCase_ = 3;
      return this;
    }
    /**
     * <code>.etcdserverpb.DeleteRangeResponse response_delete_range = 3;</code>
     */
    public Builder mergeResponseDeleteRange(io.etcd.jetcd.api.DeleteRangeResponse value) {
      if (responseDeleteRangeBuilder_ == null) {
        if (responseCase_ == 3 &&
            response_ != io.etcd.jetcd.api.DeleteRangeResponse.getDefaultInstance()) {
          response_ = io.etcd.jetcd.api.DeleteRangeResponse.newBuilder((io.etcd.jetcd.api.DeleteRangeResponse) response_)
              .mergeFrom(value).buildPartial();
        } else {
          response_ = value;
        }
        onChanged();
      } else {
        if (responseCase_ == 3) {
          responseDeleteRangeBuilder_.mergeFrom(value);
        }
        responseDeleteRangeBuilder_.setMessage(value);
      }
      responseCase_ = 3;
      return this;
    }
    /**
     * <code>.etcdserverpb.DeleteRangeResponse response_delete_range = 3;</code>
     */
    public Builder clearResponseDeleteRange() {
      if (responseDeleteRangeBuilder_ == null) {
        if (responseCase_ == 3) {
          responseCase_ = 0;
          response_ = null;
          onChanged();
        }
      } else {
        if (responseCase_ == 3) {
          responseCase_ = 0;
          response_ = null;
        }
        responseDeleteRangeBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.etcdserverpb.DeleteRangeResponse response_delete_range = 3;</code>
     */
    public io.etcd.jetcd.api.DeleteRangeResponse.Builder getResponseDeleteRangeBuilder() {
      return getResponseDeleteRangeFieldBuilder().getBuilder();
    }
    /**
     * <code>.etcdserverpb.DeleteRangeResponse response_delete_range = 3;</code>
     */
    public io.etcd.jetcd.api.DeleteRangeResponseOrBuilder getResponseDeleteRangeOrBuilder() {
      if ((responseCase_ == 3) && (responseDeleteRangeBuilder_ != null)) {
        return responseDeleteRangeBuilder_.getMessageOrBuilder();
      } else {
        if (responseCase_ == 3) {
          return (io.etcd.jetcd.api.DeleteRangeResponse) response_;
        }
        return io.etcd.jetcd.api.DeleteRangeResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.etcdserverpb.DeleteRangeResponse response_delete_range = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.etcd.jetcd.api.DeleteRangeResponse, io.etcd.jetcd.api.DeleteRangeResponse.Builder, io.etcd.jetcd.api.DeleteRangeResponseOrBuilder> 
        getResponseDeleteRangeFieldBuilder() {
      if (responseDeleteRangeBuilder_ == null) {
        if (!(responseCase_ == 3)) {
          response_ = io.etcd.jetcd.api.DeleteRangeResponse.getDefaultInstance();
        }
        responseDeleteRangeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.etcd.jetcd.api.DeleteRangeResponse, io.etcd.jetcd.api.DeleteRangeResponse.Builder, io.etcd.jetcd.api.DeleteRangeResponseOrBuilder>(
                (io.etcd.jetcd.api.DeleteRangeResponse) response_,
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      responseCase_ = 3;
      onChanged();;
      return responseDeleteRangeBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.etcd.jetcd.api.TxnResponse, io.etcd.jetcd.api.TxnResponse.Builder, io.etcd.jetcd.api.TxnResponseOrBuilder> responseTxnBuilder_;
    /**
     * <code>.etcdserverpb.TxnResponse response_txn = 4;</code>
     */
    public boolean hasResponseTxn() {
      return responseCase_ == 4;
    }
    /**
     * <code>.etcdserverpb.TxnResponse response_txn = 4;</code>
     */
    public io.etcd.jetcd.api.TxnResponse getResponseTxn() {
      if (responseTxnBuilder_ == null) {
        if (responseCase_ == 4) {
          return (io.etcd.jetcd.api.TxnResponse) response_;
        }
        return io.etcd.jetcd.api.TxnResponse.getDefaultInstance();
      } else {
        if (responseCase_ == 4) {
          return responseTxnBuilder_.getMessage();
        }
        return io.etcd.jetcd.api.TxnResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.etcdserverpb.TxnResponse response_txn = 4;</code>
     */
    public Builder setResponseTxn(io.etcd.jetcd.api.TxnResponse value) {
      if (responseTxnBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        response_ = value;
        onChanged();
      } else {
        responseTxnBuilder_.setMessage(value);
      }
      responseCase_ = 4;
      return this;
    }
    /**
     * <code>.etcdserverpb.TxnResponse response_txn = 4;</code>
     */
    public Builder setResponseTxn(
        io.etcd.jetcd.api.TxnResponse.Builder builderForValue) {
      if (responseTxnBuilder_ == null) {
        response_ = builderForValue.build();
        onChanged();
      } else {
        responseTxnBuilder_.setMessage(builderForValue.build());
      }
      responseCase_ = 4;
      return this;
    }
    /**
     * <code>.etcdserverpb.TxnResponse response_txn = 4;</code>
     */
    public Builder mergeResponseTxn(io.etcd.jetcd.api.TxnResponse value) {
      if (responseTxnBuilder_ == null) {
        if (responseCase_ == 4 &&
            response_ != io.etcd.jetcd.api.TxnResponse.getDefaultInstance()) {
          response_ = io.etcd.jetcd.api.TxnResponse.newBuilder((io.etcd.jetcd.api.TxnResponse) response_)
              .mergeFrom(value).buildPartial();
        } else {
          response_ = value;
        }
        onChanged();
      } else {
        if (responseCase_ == 4) {
          responseTxnBuilder_.mergeFrom(value);
        }
        responseTxnBuilder_.setMessage(value);
      }
      responseCase_ = 4;
      return this;
    }
    /**
     * <code>.etcdserverpb.TxnResponse response_txn = 4;</code>
     */
    public Builder clearResponseTxn() {
      if (responseTxnBuilder_ == null) {
        if (responseCase_ == 4) {
          responseCase_ = 0;
          response_ = null;
          onChanged();
        }
      } else {
        if (responseCase_ == 4) {
          responseCase_ = 0;
          response_ = null;
        }
        responseTxnBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.etcdserverpb.TxnResponse response_txn = 4;</code>
     */
    public io.etcd.jetcd.api.TxnResponse.Builder getResponseTxnBuilder() {
      return getResponseTxnFieldBuilder().getBuilder();
    }
    /**
     * <code>.etcdserverpb.TxnResponse response_txn = 4;</code>
     */
    public io.etcd.jetcd.api.TxnResponseOrBuilder getResponseTxnOrBuilder() {
      if ((responseCase_ == 4) && (responseTxnBuilder_ != null)) {
        return responseTxnBuilder_.getMessageOrBuilder();
      } else {
        if (responseCase_ == 4) {
          return (io.etcd.jetcd.api.TxnResponse) response_;
        }
        return io.etcd.jetcd.api.TxnResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.etcdserverpb.TxnResponse response_txn = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.etcd.jetcd.api.TxnResponse, io.etcd.jetcd.api.TxnResponse.Builder, io.etcd.jetcd.api.TxnResponseOrBuilder> 
        getResponseTxnFieldBuilder() {
      if (responseTxnBuilder_ == null) {
        if (!(responseCase_ == 4)) {
          response_ = io.etcd.jetcd.api.TxnResponse.getDefaultInstance();
        }
        responseTxnBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.etcd.jetcd.api.TxnResponse, io.etcd.jetcd.api.TxnResponse.Builder, io.etcd.jetcd.api.TxnResponseOrBuilder>(
                (io.etcd.jetcd.api.TxnResponse) response_,
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      responseCase_ = 4;
      onChanged();;
      return responseTxnBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:etcdserverpb.ResponseOp)
  }

  // @@protoc_insertion_point(class_scope:etcdserverpb.ResponseOp)
  private static final io.etcd.jetcd.api.ResponseOp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.etcd.jetcd.api.ResponseOp();
  }

  public static io.etcd.jetcd.api.ResponseOp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResponseOp>
      PARSER = new com.google.protobuf.AbstractParser<ResponseOp>() {
    @java.lang.Override
    public ResponseOp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ResponseOp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ResponseOp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResponseOp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.etcd.jetcd.api.ResponseOp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

